{{- if .Values.dispatcher.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "deploy-monitor.fullname" . }}-dispatcher
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "deploy-monitor.labels" . | nindent 4 }}
    app.kubernetes.io/component: dispatcher
{{- end }}
