//go:build !ignore_autogenerated

// Code generated by hand (controller-gen equivalent). DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies all properties into another ClusterRolloutState.
func (in *ClusterRolloutState) DeepCopyInto(out *ClusterRolloutState) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *ClusterRolloutState) DeepCopy() *ClusterRolloutState {
	if in == nil {
		return nil
	}
	out := new(ClusterRolloutState)
	in.DeepCopyInto(out)
	return out
}

func (in *ClusterRolloutState) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ClusterRolloutStateSpec) DeepCopyInto(out *ClusterRolloutStateSpec) {
	*out = *in
	if in.TemplateHashes != nil {
		in, out := &in.TemplateHashes, &out.TemplateHashes
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

func (in *ClusterRolloutStateSpec) DeepCopy() *ClusterRolloutStateSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterRolloutStateSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *ClusterRolloutStateStatus) DeepCopyInto(out *ClusterRolloutStateStatus) {
	*out = *in
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
}

func (in *ClusterRolloutStateStatus) DeepCopy() *ClusterRolloutStateStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterRolloutStateStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *ClusterRolloutStateList) DeepCopyInto(out *ClusterRolloutStateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterRolloutState, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *ClusterRolloutStateList) DeepCopy() *ClusterRolloutStateList {
	if in == nil {
		return nil
	}
	out := new(ClusterRolloutStateList)
	in.DeepCopyInto(out)
	return out
}

func (in *ClusterRolloutStateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties into another RolloutRecord.
func (in *RolloutRecord) DeepCopyInto(out *RolloutRecord) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *RolloutRecord) DeepCopy() *RolloutRecord {
	if in == nil {
		return nil
	}
	out := new(RolloutRecord)
	in.DeepCopyInto(out)
	return out
}

func (in *RolloutRecord) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *RolloutRecordSpec) DeepCopyInto(out *RolloutRecordSpec) {
	*out = *in
	if in.OldImages != nil {
		in, out := &in.OldImages, &out.OldImages
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.NewImages != nil {
		in, out := &in.NewImages, &out.NewImages
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.DetectedAt.DeepCopyInto(&out.DetectedAt)
}

func (in *RolloutRecordSpec) DeepCopy() *RolloutRecordSpec {
	if in == nil {
		return nil
	}
	out := new(RolloutRecordSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *RolloutRecordStatus) DeepCopyInto(out *RolloutRecordStatus) {
	*out = *in
	if in.DispatchedAt != nil {
		in, out := &in.DispatchedAt, &out.DispatchedAt
		*out = (*in).DeepCopy()
	}
	if in.DispatchTargets != nil {
		in, out := &in.DispatchTargets, &out.DispatchTargets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

func (in *RolloutRecordStatus) DeepCopy() *RolloutRecordStatus {
	if in == nil {
		return nil
	}
	out := new(RolloutRecordStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *RolloutRecordList) DeepCopyInto(out *RolloutRecordList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RolloutRecord, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *RolloutRecordList) DeepCopy() *RolloutRecordList {
	if in == nil {
		return nil
	}
	out := new(RolloutRecordList)
	in.DeepCopyInto(out)
	return out
}

func (in *RolloutRecordList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties into another MonitorConfig.
func (in *MonitorConfig) DeepCopyInto(out *MonitorConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *MonitorConfig) DeepCopy() *MonitorConfig {
	if in == nil {
		return nil
	}
	out := new(MonitorConfig)
	in.DeepCopyInto(out)
	return out
}

func (in *MonitorConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *MonitorConfigSpec) DeepCopyInto(out *MonitorConfigSpec) {
	*out = *in
	if in.NamespaceAllowlist != nil {
		in, out := &in.NamespaceAllowlist, &out.NamespaceAllowlist
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.NamespaceDenylist != nil {
		in, out := &in.NamespaceDenylist, &out.NamespaceDenylist
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

func (in *MonitorConfigSpec) DeepCopy() *MonitorConfigSpec {
	if in == nil {
		return nil
	}
	out := new(MonitorConfigSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *MonitorConfigStatus) DeepCopyInto(out *MonitorConfigStatus) {
	*out = *in
	if in.LastApplied != nil {
		in, out := &in.LastApplied, &out.LastApplied
		*out = (*in).DeepCopy()
	}
}

func (in *MonitorConfigStatus) DeepCopy() *MonitorConfigStatus {
	if in == nil {
		return nil
	}
	out := new(MonitorConfigStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *MonitorConfigList) DeepCopyInto(out *MonitorConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MonitorConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *MonitorConfigList) DeepCopy() *MonitorConfigList {
	if in == nil {
		return nil
	}
	out := new(MonitorConfigList)
	in.DeepCopyInto(out)
	return out
}

func (in *MonitorConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
